apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api-movies"
  namespace: "default"
  labels:
    app: "api-movies"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: "api-movies"
  template:
    metadata:
      labels:
        app: "api-movies"
    spec:
      containers:
      - name: "api-movies"
        image: "dgonzalez2/api-movies:1.1.0"
        ports:
          - name: http-server
            containerPort: 5000
        env:
          - name: SQLALCHEMY_DATABASE_URI
            value: postgresql://dgonzalez2:12345@postgres:5432/api-movies
          - name: SQLALCHEMY_TRACK_MODIFICATIONS
            value: "false"
          - name: SHOW_SQLALCHEMY_LOG_MESSAGES
            value: "false"
          - name: ERROR_404_HELP
            value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-movies-service"
  namespace: "default"
  labels:
    app: "api-movies"
spec:
  ports:
  - port: 5000
    targetPort: http-server
  selector:
    app: api-movies
  type: LoadBalancer

---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "api-movies"
  POSTGRES_USER: "dgonzalez2"
  POSTGRES_PASSWORD: "12345"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  namespace: "default"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:9.6.2"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

